### ISSUE TITLE
Vernemq cuttlefish error while starting using docker compose

### ISSUE THREAD

**Issue by codersidprogrammer** [gojek/vernemq#52]
### Issue
[Docker hub](https://hub.docker.com/layers/gojektech/vernemq/latest/images/sha256-32df84fce12f63c9c0dc1fa3c9dccdf3ecdb78983bcc6d9fb188aba8fb095410?context=explore)
Hi there, i try to use your version of vernemq that downloaded from your public docker hub. But i got some error while starting. Redis as part of main component is up and run well.

### Environment

- VerneMQ Version: gojektech/vernemq:latest
- OS: Ubuntu 20
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone:

### Expected behaviour
Container run and its log show vernemq logo
```
13:32:07.721 [info] loaded 0 subscriptions into vmq_reg_trie 
13:32:07.726 [info] cluster event handler 'vmq_cluster' registered
```

### Actual behaviour
But i got error message while run `docker-compose up`
```
Error generating config with cuttlefish
run vernemq config generate -l debug for more information.
```

### Docker compose
```
version: '3.6'
  
services:

  vernemq-1:
    container_name: vernemq-1
    image: gojektech/vernemq
    # command: ["vernemq", "config", "generate","-l","debug","&&","start_vernemq"]
    ports:
      - '1883:1883'
      - '8080:8080'
      - '8888:8888'
    environment:
    # I tried to use point env or non point but resulting same error

    # I use this from https://courier-gojek.gitbook.io/vernemq/configuring-vernemq/messagepassing
    # msg_queue_redis_shards_connect_options
    #- DOCKER_VERNEMQ_MSG_QUEUE_REDIS_SHARDS_CONNECT_OPTIONS=[[{host,"172.16.41.107"},{port,6378},{database,0}]]
   
    # main_queue_workers_per_redis_shard
    #- DOCKER_VERNEMQ_MAIN_QUEUE_WORKERS_PER_REDIS_SHARD=1

    # redis_queue_sleep_interval
    # - DOCKER_VERNEMQ_REDIS_QUEUE_SLEEP_INTERVAL=0
      

   # this env i use has same result while use your image. But if it come from official vernemq, it run well
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: 'on'
      DOCKER_VERNEMQ_PLUGINS__VMQ_ACL: 'off'
      DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD: 'off'
      DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY: 'on'
      #DOCKER_VERNEMQ_VMQ_DIVERSITY__AUTH_REDIS__ENABLED: 'on'
      DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__HOST: 172.16.41.107
      DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__PORT: '6378'
      #DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__PASSWORD: admin2021
      DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__DATABASE: '0'
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
    networks:
      - redis_network

networks:
  redis_network:
    external:
      name: xops_server_redisnet
```
