### ISSUE TITLE
Issue: Messages not delivered when subscribing to a topic

### ISSUE THREAD

**Issue by heldiapriadi** [gojek/vernemq#57]
### Issue

I'm experiencing an issue where messages are not being delivered when subscribing to a specific topic in system. 

### Steps Taken:

1. Subscribed to the topic.
2. Waited for messages to be delivered when events occur related to that topic.
3. Publish messages to the topic.

### Observed Behavior:

- I'm not receiving any messages when events occur in the topic I subscribed to.
- However, it's worth noting that retained messages work as expected, and there are no issues with them.

### Environment

- VerneMQ Version: gojektech/vernemq:latest
- OS: Ubuntu 22
- Erlang/OTP version (if building from source):
- VerneMQ configuration (vernemq.conf) or the changes from the default
- Cluster size/standalone:

### Docker Compose
```
version: '3.8'
services:
  vernemqgojek:
    image: gojektech/vernemq
    container_name: vmq-gojek
    environment:
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: 'off'
      DOCKER_VERNEMQ_PLUGINS__VMQ_ACL: 'off'
      DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD: 'off'
      DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY: 'on'
      DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL: debug
      #      DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT: true

      DOCKER_VERNEMQ_PLUGINS__VMQ_ENHANCED_AUTH: 'on'
      DOCKER_VERNEMQ_VMQ_ENHANCED_AUTH__ENABLE_JWT_AUTH: true
      DOCKER_VERNEMQ_VMQ_ENHANCED_AUTH__SECRET_KEY: 'key'
      DOCKER_VERNEMQ_VMQ_ENHANCED_AUTH__ENABLE_ACL_HOOKS: true

      DOCKER_VERNEMQ_REDIS_SENTINEL_ENDPOINTS: '[{"redis-sentinel-1", 26379},{"redis-sentinel-2", 26379},{"redis-sentinel-3", 26379}]'
      DOCKER_VERNEMQ_MSG_QUEUE_REDIS_SHARDS_CONNECT_OPTIONS: '[[{host,"redis-master"},{port,6379},{database,1}]]'
      DOCKER_VERNEMQ_MAIN_QUEUE_WORKERS_PER_REDIS_SHARD: 1
      DOCKER_VERNEMQ_REDIS_QUEUE_SLEEP_INTERVAL: 0
    ports:
      - "1884:1883"
      - "8081:8080"
      - "8889:8888"
```
